dist: xenial
sudo: false
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - lcov

script:
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake .
  - cmake --build . --target animeditor
  - cmake --build . --target libanimeditor-test
  - ./libanimeditor-test

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --remove coverage.info '*/test/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info
